spring.application.name=rinha-de-backend-2025
rinha.default.url=http://localhost:8183/category/rinha/default
rinha.fallback.url=http://localhost:8183/category/rinha/fallback
spring.redis.host=localhost
spring.redis.port=6379

